// Generates a build version in format yyyy.mm.dd.hh.mi and writes to src/lib/version.ts
import fs from 'fs';
import path from 'path';

function pad(n) { return n.toString().padStart(2, '0'); }

const now = new Date();
const version = [
  now.getFullYear(),
  pad(now.getMonth() + 1),
  pad(now.getDate()),
  pad(now.getHours()),
  pad(now.getMinutes())
].join('.');

const banner = `// This file is auto-generated by scripts/generate-version.js on ${now.toISOString()}\n`;
const content = `${banner}export const BUILD_VERSION = '${version}';\n`;

const outFile = path.resolve(process.cwd(), 'src', 'lib', 'version.ts');
fs.writeFileSync(outFile, content, 'utf8');
console.log('Generated build version:', version, '->', outFile);
